### ISSUE TITLE
[DEPR]: Cypress E2E tests

### ISSUE THREAD

**Issue by sarina** [openedx/cypress-e2e-tests#123]
### Proposal Date

2024-07-30

### Target Ticket Acceptance Date

2024-08-13

### Earliest Open edX Named Release Without This Functionality

Sumac - 2024-10

### Rationale

Cypress e2e tests are no longer used in the Open edX ecosystem. The last substantive commit to the repo was April 2022.

### Removal

The https://github.com/openedx/cypress-e2e-tests repo will be moved to `openedx-unsupported` and archived

### Replacement

No replacement is planned for Cypress

### Deprecation

No code will be marked for deprecation

**Comment by sarina** [comment]
Discourse post: https://discuss.openedx.org/t/deprecation-removal-cypress-e2e-tests/13544

**Comment by cmltaWt0** [comment]
@sarina 

I would like to step up and propose myself as a maintainer of the repository. Within Raccoon Gang, we've done some work using this repo to automate smoke testing.

Currently, we are discussing a potential switch to Playwright, as it may be better suited for long regression scenarios, but this discussion is ongoing.

My intention is to automate the release testing process so that we can quickly re-test major scenarios. I’m willing to start this work with this repo.

Additionally, I’m curious about its value to our community. Is anyone else using it? Would reviving the repo and adding general tests for Open edX be valuable beyond the BTR group?

**Comment by jristau1984** [comment]
Cypress tests are used at 2U still, but new test creation is largely not happening.  There are a few suites which run during deployment time.

**Comment by sarina** [comment]
@cmltaWt0 thanks for stepping up to maintain this repo! I will close this DEPR ticket and you can nominate yourself on the forums to extend your rights to this repo.

> Additionally, I’m curious about its value to our community. Is anyone else using it? Would reviving the repo and adding general tests for Open edX be valuable beyond the BTR group?

I think that'll be good to explore as you take on maintenance work. @jristau1984 has given a data point already!

**Comment by cmltaWt0** [comment]
@sarina sure, thanks for the ping! We are adapting our cypress tests for Sumac and Teak right now and I'm going to port a lot of tests to the repo (along with the cypress version upgrade). Just finishing the job internally.

**Comment by cmltaWt0** [comment]
@bszabo sorry for the late response. Missed it.

We are going to contribute the following list of tests (screenshot below).

<img width="1166" alt="Image" src="https://github.com/user-attachments/assets/10844566-05b7-48bd-b333-69e4be412881" />
